In [128]:
import requests
import random
from scrapy.http import TextResponse
import pandas as pd

In [132]:
#Used Scrapeops site to generate fake headers so the website can't revoke access due to same headers

#response = requests.get(
  #url='https://headers.scrapeops.io/v1/browser-headers',
  #params={
      #'api_key': 'aecb29db-aaad-4ea2-ae8f-e98b2e046acb',
      #'num_headers': '2'}
#)

#print('Response Body: ', response.json())

In [47]:
#Using requests and scrapy library to access the website and scrape the data on the first page

url='https://www.amazon.in/s?k=mobiles+5g&crid=2T9LPN1XBSU8W&sprefix=mobiles%2Caps%2C185&ref=nb_sb_ss_ts-doa-p_8_7'
header=response.json()['result'][3]
r=requests.get(url,headers=header)
response=TextResponse(r.url,body=r.text,encoding="utf-8")

In [134]:
#Creating empty list in order to feed the scraped data into their respective list
title=[]
price=[]
rating=[]
# Using for loops to access the particular class from which we'll scaped the title,price and rating
for x in response.css('div.sg-row')[3:]: 
    if x.css('img.s-image')==[]:
        continue
    elif x.css('img.s-image')=='None':
        continue
    else:
        #Gonna append the output in their respective list which we'll use to create a dataframe
        
        title.append(x.css('img.s-image').xpath('@alt').get())
        price.append(x.css('span.a-price-whole::text').get())
        rating.append(f"{x.css('span.a-icon-alt::text').get().split()[0]}/5")
        
#Using Pandas library to create a dataframe with the help of list in which appended the data above

df=pd.DataFrame(title).rename(columns={0:'Title'})
df['Price']=price
df['Rating']=rating
df

                                                Title   Price Rating
0   Samsung Galaxy M14 5G (Smoky Teal, 6GB, 128GB ...  15,990  3.9/5
1   realme narzo 60 5G (Mars Orange,8GB+128GB) 90H...  17,999  3.8/5
2   OnePlus Nord CE 3 Lite 5G (Pastel Lime, 8GB RA...  21,999  4.1/5
3   realme narzo 60 5G (Mars Orange,8GB+256GB) | 9...  19,999  3.8/5
4   Samsung Galaxy M33 5G (Deep Ocean Blue, 8GB, 1...  18,499  4.1/5
5   Samsung Galaxy M14 5G (Berry Blue, 6GB, 128GB ...  15,990  3.9/5
6   OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...  17,999  4.2/5
7   Oppo A78 5G (Glowing Black, 8GB RAM, 128 Stora...  18,999  4.1/5
8   Samsung Galaxy M14 5G (ICY Silver, 6GB, 128GB ...  15,990  3.9/5
9   iQOO Z6 Lite 5G (Stellar Green, 6GB RAM, 128GB...  13,999  4.0/5
10  iQOO Z7s 5G by vivo (Norway Blue, 8GB RAM, 128...  19,999  4.1/5
11  iQOO Z6 Lite 5G (Mystic Night, 6GB RAM, 128GB ...  13,999  4.0/5
12  Samsung Galaxy M34 5G (Midnight Blue, 6GB, 128...  18,999  3.7/5
13  Redmi 11 Prime 5G (Thunder Black, 4GB RAM, 64G...  12,999  3.9/5
14  Samsung Galaxy M33 5G (Mystique Green, 8GB, 12...  18,499  4.1/5
15  OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...  17,999  4.2/5

In [135]:
#Using for loops to access the link to the product image

#Commented it out because the output for just links which we copied and pasted in the below links for images

#for x in response.css('img.s-image').xpath('@src'):
    #print(f'<img src="{x.get()}" >')

<img src="https://m.media-amazon.com/images/I/91zMokvCNuL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/81SvInWFWWL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/61QRgOgBx0L._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/81SvInWFWWL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/81xvGbBFNhL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/91HRACirFrL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/71V--WZVUIL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/81LrmorQeQL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/817WWpaFo1L._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/61VbKHdE0rL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/71k3gOik46L._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/61M0tGMbBPL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/91fonhAtoAL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/81lAth+jv+L._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/81I3w4J6yjL._AC_UY218_.jpg" >
<img src="https://m.media-amazon.com/images/I/71AvQd3VzqL._AC_UY218_.jpg" >
​